### ISSUE TITLE
No control over name

### ISSUE THREAD

**Issue by scott-grimes** [avinor/terraform-azurerm-storage-account#12]
As an engineer I would expect to be able to control what parameters are given when creating resources. Right now users do not actually have control over the name a storage account will have. The `var.name` which is passed has 6 random characters appended to it by default. 

This is unfortunate because our naming scheme creates names with lengths ~20 char long, but with the additional characters the module breaks and throws errors

`Storage account names must be between 3 and 24 characters in length and only use numbers and lowercase letters`

I have opened a PR that provides the ability for devs to specify the exact name they want

https://github.com/avinor/terraform-azurerm-storage-account/pull/11

**Comment by InsulaVentus** [comment]
This was fixed in #11
